### ISSUE TITLE
libuv build failure

### ISSUE THREAD

**Issue by natj** [natj/csc-ss14#1]
``` julia
    CC src/flisp/string.o
    CC src/flisp/equalhash.o
    CC src/flisp/table.o
    CC src/flisp/iostream.o
    CC src/flisp/julia_extensions.o
    LINK src/flisp/libflisp.a
    CC src/flisp/flmain.o
    LINK src/flisp/flisp
/homeappl/home/trng08/julia/usr/lib/libuv.a(libuv_la-core.o):(.note.stapsdt+0x24): undefined reference to `uv_tick__start_semaphore'
/homeappl/home/trng08/julia/usr/lib/libuv.a(libuv_la-core.o):(.note.stapsdt+0x70): undefined reference to `uv_tick__stop_semaphore'
collect2: error: ld returned 1 exit status
make[3]: *** [flisp] Error 1
make[2]: *** [flisp/libflisp.a] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
trng08@sisu-login2:~/julia> 
```

**Comment by psanan** [comment]
I've encountered this same issue - any update since this was posted?

**Comment by natj** [comment]
I encountered this problem when trying to compile julia into our CSC supercomputer where there is separate login node. I think the problem was that libuv had some problems with the distinction of separate computing nodes and login/compiling node.

Since then I have been able to compile it without problem for smaller computing clusters (also with separate login nodes) so I dunno if the problem remained as I have not worked with the first computer for a while. If you are in a similar situation I recommend you write to the julia-users (or julia-devs) google group, they might know better how to deal with this.

**Comment by psanan** [comment]
Thanks : ] I am compiling in a similar environment (a login node on a supercomputer). Which compilers have you succeeded in using on clusters where you got things working?

**Comment by natj** [comment]
Currently I did everything "the dirty way" and compiled every library (so no system BLAS or anything was linked) with gnu compilers. I also have no clue why I got the libuv error with the first cluster but everything went fine with the second one (it basically worked out of the box). Anyway, at some point I have to get this also done for the first cluster so if you happen to find anything, please let me know also!

There might be some fundamental problem here so I would advise you to ask the developers in julia-dev.

**Comment by psanan** [comment]
As an update, we got this to work (with the release-0.3 branch, master seems fine) with the change described in the julia-users discussion below (disabling dtrace in libuv's configure). The master branch doesn't seem to have this problem anymore.
https://groups.google.com/forum/#!topic/julia-users/LUVVEfydAso

**Comment by natj** [comment]
Many thanks for linking the solution!

**Comment by psanan** [comment]
(Note that at the time of this writing, the test suite still doesn't pass, so there might still be issues with the build procedure)
